### PR TITLE
Made it possible to actually check the help info for the command

### PR DESCRIPTION
**Pull request by GriffinG1**
Seriously, learn class naming.

### CODE REVIEW

**Comment by Bluscream** [comment]
Your changes are not well documented.

**Comment by GriffinG1** [comment]
Bullshit, you merged a PR from lyric that's literally titled "Improvements"

**Comment by Bluscream** [comment]
I was just joking, but before i merge this i'm gonna push my local commits

**Comment by LyricLy** [comment]
🤔

**Pull request merged**
